import { PayloadAction, createSlice } from '@reduxjs/toolkit';

// Define the initial state for the theme
const initialState = {
    isMenuOpen: false,
    theme: 'light', // Default theme is set to 'light'
};

const navbarSlice = createSlice({
    name: 'navbar',
    initialState,
    reducers: {
        // Reducer to toggle between light and dark mode
        toggleMenu: (state) => {
            state.isMenuOpen = !state.isMenuOpen;
        },
        setTheme: (state, action: PayloadAction<'light' | 'dark'>) => {
            state.theme = action.payload;
          },
    },
});

// Export the action generated by the slice
export const {  toggleMenu,  setTheme } = navbarSlice.actions;

// Export the reducer to be used in the store configuration
export default navbarSlice.reducer;