import { createSlice } from '@reduxjs/toolkit';

// Define the initial state for the theme
const initialState = {
    isMenuOpen: false,
   
};

const navbarSlice = createSlice({
    name: 'navbar',
    initialState,
    reducers: {
        // Reducer to toggle between light and dark mode
        toggleMenu: (state) => {
            state.isMenuOpen = !state.isMenuOpen;
        },
        
    },
});

// Export the action generated by the slice
export const {  toggleMenu } = navbarSlice.actions;

// Export the reducer to be used in the store configuration
export default navbarSlice.reducer;